### ISSUE TITLE
run dev proxy  non-object 脚本错误，望高手指点

### ISSUE THREAD

**Issue by dongdan002** [chiflix/splayerx#1036]
运行npm run dev 时出现如下脚本错误，build正常，但安装完splayer后点击不出现界面，只在后台运行。新手研究播放器，目前4.4.0、4.4.3版本都有这个问题，希望大家能指点一下。
App threw an error during load
  TypeError: Cannot create proxy with a non-object as target or handler
      at Module../src/main/helpers/mediaTasksPlugin.ts (F:\TestProjects\splayer\splayerx-4.4.0\dist\electron\main.js:29135:23)
      at __webpack_require__ (F:\TestProjects\splayer\splayerx-4.4.0\dist\electron\main.js:21:30)
      at Module../src/main/index.js (F:\TestProjects\splayer\splayerx-4.4.0\dist\electron\main.js:29493:84)
      at __webpack_require__ (F:\TestProjects\splayer\splayerx-4.4.0\dist\electron\main.js:21:30)
      at Object../src/main/index.dev.js (F:\TestProjects\splayer\splayerx-4.4.0\dist\electron\main.js:29459:1)
      at __webpack_require__ (F:\TestProjects\splayer\splayerx-4.4.0\dist\electron\main.js:21:30)
      at Object.0 (F:\TestProjects\splayer\splayerx-4.4.0\dist\electron\main.js:32679:1)
      at __webpack_require__ (F:\TestProjects\splayer\splayerx-4.4.0\dist\electron\main.js:21:30)
      at F:\TestProjects\splayer\splayerx-4.4.0\dist\electron\main.js:85:18
      at Object.<anonymous> (F:\TestProjects\splayer\splayerx-4.4.0\dist\electron\main.js:88:10)

**Comment by ipy** [comment]
看症状像 electron 没有安装成功？

**Comment by wood-j** [comment]
一样现象，估计是大佬们还没考虑兼容吧
Manjaro Linux x64
node v12.13.0
src release: 4.6.1

**Comment by ipy** [comment]
Linux 目前暂未支持
